version: '3.8'

services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    expose:
      - '5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
