version: '3.8'

services:
  svelte-app:
    image: node:20
    ports:
      - '5173:5173'
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
